"""Fondations de MetaHarness V0."""

from .agent import (
    AgentResult,
    CodexAgent,
    CodexAuthStatus,
    check_codex_authentication,
)
from .claude import (
    ClaudeAgentError,
    ClaudeAuthStatus,
    ClaudeCodeAgent,
    ClaudeCommittedError,
    ClaudeResult,
    ClaudeRuntimeError,
    build_claude_environment,
    check_claude_authentication,
    prepare_claude_home,
)
from .approval import (
    ApprovalDecision,
    ApprovalError,
    PlanApproval,
    PlanIdentity,
    compute_plan_identity,
    compute_plan_identity_from_run,
    read_plan_approval,
    wait_for_plan_approval,
    write_plan_approval,
)
from .config import ConfigError, load_config
from .environment import EnvironmentFileError, build_runtime_environment, parse_env_file
from .context import (
    ContextBundle,
    ContextExcerpt,
    build_context,
    build_context_bundle,
    render_context,
)
from .evidence import EvidenceBundle, collect_evidence
from .commit_gate import (
    CommitSafetyError,
    CommitSafetyResult,
    DeferredVerification,
    accepted_step_record,
    assert_deferred_verifications_resolved,
    commit_gate,
    commit_safety_gate,
    parse_deferred_verification,
    unresolved_deferred_verifications,
    validate_commit_safety,
)
from .gitops import (
    commit_candidate_tree,
    commit_repair_tree,
    commit_revision_tree,
    commit_step_tree,
    commit_tree,
    validate_linear_commit_chain,
)
from .models import (
    AgentConfig,
    ApprovalConfig,
    CheckConfig,
    CheckCatalogEntry,
    TrustedCheckConfig,
    ClaudeRuntimeConfig,
    CodexRuntimeConfig,
    ContextConfig,
    EnvironmentConfig,
    ExecutionMode,
    ExecutionSelectionV5,
    ExecutionSelectionV3,
    HarnessConfig,
    ImplementationStep,
    LLMEndpointConfig,
    PlanDecision,
    PlanningConfig,
    PromptBudgetConfig,
    PublishConfig,
    RevisionConfig,
    RepositoryConfig,
    ReviewRoute,
    ReviewVerdict,
    RunStatus,
    RunCycle,
    TaskPlanV2,
    WorkspaceSetupCommand,
    SelectedProfile,
    StepExecutionSelection,
)
from .trace import (
    FanoutTraceSink,
    JsonlTraceSink,
    NullTraceSink,
    TraceEvent,
    TraceSink,
    TraceStream,
)
from .prompt_contracts import (
    PromptPayload,
    PromptSection,
    build_check_repair_payload,
    build_final_review_payload,
    build_implementer_payload,
    build_planner_payload,
    build_semantic_revision_payload,
)
from .orchestrator import Orchestrator, run_orchestrator
from .orchestration.check_repair import CheckRepairAttempt, CheckRepairResult
from .review import Reviewer, ReviewParseError, ReviewResult, parse_review
from .result import RunResult
from .run_options import (
    RunOptions,
    RunOptionsConflict,
    RunOptionsError,
    effective_run_config,
    read_run_options_with_sha256,
)
from .state import RunStateStore
from .validation import CheckResult, ValidationError, run_check_preflights, run_checks
from .workspace import WorkspaceSetupError, WorkspaceSetupResult, prepare_workspace

__all__ = [
    "AgentConfig",
    "AgentResult",
    "ApprovalConfig",
    "ApprovalDecision",
    "ApprovalError",
    "CheckConfig",
    "CheckCatalogEntry",
    "TrustedCheckConfig",
    "ClaudeAgentError",
    "ClaudeAuthStatus",
    "ClaudeCodeAgent",
    "ClaudeCommittedError",
    "ClaudeResult",
    "ClaudeRuntimeConfig",
    "ClaudeRuntimeError",
    "CodexRuntimeConfig",
    "CheckResult",
    "CheckRepairAttempt",
    "CheckRepairResult",
    "CodexAgent",
    "CodexAuthStatus",
    "ConfigError",
    "ContextBundle",
    "ContextConfig",
    "EnvironmentConfig",
    "ExecutionMode",
    "ExecutionSelectionV5",
    "ExecutionSelectionV3",
    "ContextExcerpt",
    "EvidenceBundle",
    "EnvironmentFileError",
    "HarnessConfig",
    "ImplementationStep",
    "LLMEndpointConfig",
    "PlanDecision",
    "PlanningConfig",
    "PromptBudgetConfig",
    "PromptPayload",
    "PromptSection",
    "PublishConfig",
    "RevisionConfig",
    "RepositoryConfig",
    "PlanApproval",
    "PlanIdentity",
    "ReviewParseError",
    "ReviewResult",
    "ReviewRoute",
    "ReviewVerdict",
    "Reviewer",
    "RunStateStore",
    "RunResult",
    "RunOptions",
    "RunOptionsConflict",
    "RunOptionsError",
    "RunStatus",
    "RunCycle",
    "TaskPlanV2",
    "WorkspaceSetupCommand",
    "SelectedProfile",
    "StepExecutionSelection",
    "WorkspaceSetupError",
    "WorkspaceSetupResult",
    "Orchestrator",
    "ValidationError",
    "build_context",
    "build_context_bundle",
    "build_claude_environment",
    "build_runtime_environment",
    "collect_evidence",
    "CommitSafetyError",
    "CommitSafetyResult",
    "DeferredVerification",
    "accepted_step_record",
    "assert_deferred_verifications_resolved",
    "commit_gate",
    "commit_safety_gate",
    "parse_deferred_verification",
    "unresolved_deferred_verifications",
    "validate_commit_safety",
    "commit_tree",
    "commit_candidate_tree",
    "commit_step_tree",
    "commit_repair_tree",
    "commit_revision_tree",
    "validate_linear_commit_chain",
    "check_codex_authentication",
    "check_claude_authentication",
    "compute_plan_identity",
    "compute_plan_identity_from_run",
    "load_config",
    "parse_review",
    "parse_env_file",
    "render_context",
    "read_plan_approval",
    "run_orchestrator",
    "run_checks",
    "run_check_preflights",
    "wait_for_plan_approval",
    "write_plan_approval",
    "prepare_workspace",
    "prepare_claude_home",
    "build_planner_payload",
    "build_implementer_payload",
    "build_check_repair_payload",
    "build_semantic_revision_payload",
    "build_final_review_payload",
    "effective_run_config",
    "read_run_options_with_sha256",
]
